import Head from "next/head";
import {
    getHomeSection,
    getSocialLinks,
    getAboutSection,
    getFeaturedProjects,
    getJsProjects,
    getCtaSection,
} from "@/lib/sanity.client";

import MobileHeader from "../components/MobileHeader";

export default function Home({
    homeSection,
    socialLinks,
    aboutSection,
    featuredProjects,
    jsProjects,
    ctaSection,
}) {
    console.log(
        homeSection,
        socialLinks,
        aboutSection,
        featuredProjects,
        jsProjects,
        ctaSection
    );
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileHeader />
            <h1 className="text-red-500">Personal Portfolio</h1>
        </>
    );
}

export async function getStaticProps() {
    const [
        homeSection,
        socialLinks,
        aboutSection,
        featuredProjects,
        jsProjects,
        ctaSection,
    ] = await Promise.all([
        getHomeSection(),
        getSocialLinks(),
        getAboutSection(),
        getFeaturedProjects(),
        getJsProjects(),
        getCtaSection(),
    ]);

    return {
        props: {
            homeSection,
            socialLinks,
            aboutSection,
            featuredProjects,
            jsProjects,
            ctaSection,
        },
    };
}
