import Head from "next/head";
import {
    getHomeSection,
    getSocialLinks,
    getAboutSection,
    getFeaturedProjects,
    getJsProjects,
    getCtaSection,
} from "@/lib/sanity.client";

import MobileHeader from "../components/MobileHeader";
import DesktopHeader from "../components/DesktopHeader";
import DesktopSocialLinks from "@/components/DesktopSocialLinks";
import HomeSection from "../components/HomeSection";
import AboutSection from "../components/AboutSection";
import WorkSection from "../components/WorkSection";
import JsProjectsSection from "../components/JsProjectsSection";
import CtaSection from "../components/CtaSection";
import Footer from "../components/Footer";

export default function Home({
    homeSection,
    socialLinks,
    aboutSection,
    featuredProjects,
    jsProjects,
    ctaSection,
}) {
    console.log(
        homeSection,
        socialLinks,
        aboutSection,
        featuredProjects,
        jsProjects,
        ctaSection
    );
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileHeader socialLinks={socialLinks} />
            <DesktopHeader />
            <DesktopSocialLinks socialLinks={socialLinks} />
            <main>
                <HomeSection homeSection={homeSection} />
                <AboutSection aboutSection={aboutSection} />
                <WorkSection featuredProjects={featuredProjects} />
                <JsProjectsSection jsProjects={jsProjects} />
                <CtaSection ctaSection={ctaSection} />
            </main>
            <Footer />
        </>
    );
}

export async function getStaticProps() {
    const [
        homeSection,
        socialLinks,
        aboutSection,
        featuredProjects,
        jsProjects,
        ctaSection,
    ] = await Promise.all([
        getHomeSection(),
        getSocialLinks(),
        getAboutSection(),
        getFeaturedProjects(),
        getJsProjects(),
        getCtaSection(),
    ]);

    return {
        props: {
            homeSection,
            socialLinks,
            aboutSection,
            featuredProjects,
            jsProjects,
            ctaSection,
        },
    };
}
