import { useState, useEffect, useRef } from "react";

import Head from "next/head";
import {
    getHomeSection,
    getSocialLinks,
    getAboutSection,
    getFeaturedProjects,
    getJsProjects,
    getCtaSection,
} from "@/lib/sanity.client";

import Header from "../components/Header";
import HomeSection from "../components/HomeSection";
import AboutSection from "../components/AboutSection";
import WorkSection from "../components/WorkSection";
import JsProjectsSection from "../components/JsProjectsSection";
import CtaSection from "../components/CtaSection";
import Footer from "../components/Footer";

export default function Home({
    homeSection,
    socialLinks,
    aboutSection,
    featuredProjects,
    jsProjects,
    ctaSection,
}) {
    const [isNavVisible, setIsNavVisible] = useState(false);

    const homeSectionRef = useRef(null);
    const aboutSectionRef = useRef(null);
    const workSectionRef = useRef(null);
    const ctaSectionRef = useRef(null);

    useEffect(() => {
        document.body.style.overflow = isNavVisible ? "hidden" : "";
    }, [isNavVisible]);

    function scrollToSection(ref) {
        return (e) => {
            e.preventDefault();
            setIsNavVisible(false);
            ref.current?.scrollIntoView({ behavior: "smooth" });
        };
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header
                isNavVisible={isNavVisible}
                setIsNavVisible={setIsNavVisible}
                socialLinks={socialLinks}
                scrollToHome={scrollToSection(homeSectionRef)}
                scrollToAbout={scrollToSection(aboutSectionRef)}
                scrollToWork={scrollToSection(workSectionRef)}
                scrollToCta={scrollToSection(ctaSectionRef)}
            />
            <main>
                <HomeSection ref={homeSectionRef} homeSection={homeSection} />
                <AboutSection
                    ref={aboutSectionRef}
                    aboutSection={aboutSection}
                    scrollToWork={scrollToSection(workSectionRef)}
                    scrollToCta={scrollToSection(ctaSectionRef)}
                />
                <WorkSection
                    ref={workSectionRef}
                    featuredProjects={featuredProjects}
                />
                <JsProjectsSection jsProjects={jsProjects} />
                <CtaSection ref={ctaSectionRef} ctaSection={ctaSection} />
            </main>
            <Footer />
        </>
    );
}

export async function getStaticProps() {
    const [
        homeSection,
        socialLinks,
        aboutSection,
        featuredProjects,
        jsProjects,
        ctaSection,
    ] = await Promise.all([
        getHomeSection(),
        getSocialLinks(),
        getAboutSection(),
        getFeaturedProjects(),
        getJsProjects(),
        getCtaSection(),
    ]);

    return {
        props: {
            homeSection,
            socialLinks,
            aboutSection,
            featuredProjects,
            jsProjects,
            ctaSection,
        },
    };
}
